<!--
%\VignetteEngine{knitr}
%\VignetteIndexEntry{Introduction to qtlpvl}
-->

```{r, echo = FALSE, message = FALSE}
library(qtlpvl)
knitr::opts_chunk$set(
  comment = "#>",
  error = FALSE,
  tidy = FALSE)
```

# Introduction to qtlpvl

## Data

```{r}
data(hyper)
hyper <- calc.genoprob(hyper)
geno <- pull.geno(hyper, chr="1")
genotype1 <- geno[,6]
genotype2 <- geno[,12]
n <- length(genotype1)
p <- 10
p1 <- floor(p/2)
G1 <- matrix(genotype1, n, p1)
G2 <- -matrix(genotype2, n, p-p1)
G <- cbind(G1, G2)
Y <- matrix(rnorm(n*p, sd=0.5), n, p)
Y <- Y + G
```

## `scanone.mvn`
```{r}
out <- scanone.mvn(hyper, Y, chr="17")
summary(out)
plot(out)
```

## test of 1 vs 2 QTL `testpleio.1vs2`
```{r}
obj <- testpleio.1vs2(cross=hyper, Y=Y, chr="1", n.simu=100,
                      region.l=19, region.r=90)
summary(obj)
plot(obj)
```



## test of 1 vs p QTL `testpleio.1vsp`
```{r}
obj2 <- testpleio.1vsp(cross=hyper, Y=Y, chr="1", n.simu=100)
summary(obj2)
plot(obj2)
```


## plot LOD score with sign `plotLODsign` 
```{r}
#####
data(listeria)
geno <- pull.geno(listeria, chr="1")
genotype1 <- geno[,7]
genotype2 <- geno[,10]
n <- length(genotype1)
p <- 100
p1 <- floor(p/2)
G1 <- matrix(genotype1, n, p1)
G2 <- matrix(genotype2, n, p-p1)
G2[G2==3] <- 2
G2 <- -G2
G <- cbind(G1, G2)
Y <- matrix(rnorm(n*p,sd=0.5),n,p)
Y <- Y + G
plotGenetpattern(Y, genotype1)
```

## plot Genetic Pattern `plotGenetpattern`
```{r}
data(listeria)
listeria <- calc.genoprob(listeria)
geno <- pull.geno(listeria, chr="1")
genotype1 <- geno[,7]
genotype2 <- geno[,10]
n <- length(genotype1)
p <- 100
p1 <- floor(p/2)
G1 <- matrix(genotype1, n, p1)
G2 <- -matrix(genotype2, n, p-p1)
G <- cbind(G1, G2)
Y <- matrix(rnorm(n*p,sd=0.5),n,p)
Y <- Y + G
plotLODsign(listeria, Y, chr="1")

```
